run:
  deadline: 1m # default 1m
  tests: true # default true

linters-settings:
  errcheck:
    check-type-assertions: true # default false
    check-blank: true # default false
    ignore: "fmt:.*" # default fmt:.*
    exclude: "" # default ""
  govet:
    disable-all: true
    enable:
      - asmdecl
      - assign
      - atomic
      - atomicalign
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shadow
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    settings:
      shadow:
        strict: true # default false
  structcheck:
    exported-fields: true # default false
  unused:
    check-exported: true # default false
  varcheck:
    exported-fields: true # default false
  dupl:
    threshold: 150 # default 150
  funlen:
    lines: 60 # default 60
    statements: 40 # default 40
  goconst:
    min-len: 3 # default 3
    min-occurrences: 3 # default 3
  gocritic:
    settings:
      captLocal:
        paramsOnly: false # default true
      elseif:
        skipBalanced: false # default true
      underef:
        skipRecvDeref: false # default true
  gocyclo:
    min-complexity: 15 # default 30
  goimports:
    local-prefixes: github.com/maratori/pt
  golint:
    min-confidence: 0.8 # default 0.8
  lll:
    line-length: 120 # default 120
  maligned:
    suggest-new: true # default false
  misspell:
    locale: us
    ignore-words: "" # default: ""
  nakedret:
    max-func-lines: 0 # default 30
  prealloc:
    simple: false # default true
    range-loops: true # default true
    for-loops: true # default false
  unparam:
    check-exported: true # default false

linters:
  disable-all: true
  enable:
    ## enabled by default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    #- unused # false positives
    - varcheck
    ## disabled by default
    - bodyclose
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - golint
    - gosec
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - unconvert
    - unparam
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
