name: CI
on:
  workflow_dispatch:
    inputs:
      debug_ssh:
        description: "Enable SSH debug with tmate, see https://github.com/marketplace/actions/debugging-with-tmate"
        required: false
        type: boolean
        default: false
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1" # Each Monday

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.13"
      - name: Debug with tmate SSH if enabled
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_ssh }}
        uses: mxschmitt/action-tmate@v3
      - run: go test -race -p=8 -parallel=8 -tags=example -coverpkg ./... -coverprofile=coverage.out ./...
      - uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: "v1.19"
          args: "--out-format=line-number"

  check-tidy:
    name: go mod tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.13"
      - name: Check that go.mod and go.sum are tidy
        run: |
          go mod tidy
          if [[ `git status --porcelain go.mod` ]]; then git diff -- go.mod ; echo "go.mod is outdated, please run go mod tidy" ; exit 1; fi
          if [[ `git status --porcelain go.sum` ]]; then git diff -- go.sum ; echo "go.sum is outdated, please run go mod tidy" ; exit 1; fi
